spring:
  application:
    name: cheatsheet

  datasource:
    url: jdbc:h2:mem:test
    username: test
    password: test

  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT}
      region:
        static: ${AWS_REGION:us-east-2}
      credentials:
        access-key: ${AWS_ACCESS_KEY:test}
        secret-key: ${AWS_SECRET_KEY:test}

      s3:
        region: ${AWS_REGION:us-east-2}
        bucket-name: ${AWS_BUCKET:test}
        path-style-access-enabled: true